# This file set up the AustinAnimalCenter deploy on Render.
services:
  - type: web
    name: animal-shelter-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python DashForAnimalShelter.py
    envVars:
      - key: PORT
        value: 10000
